name: test

on: [push, pull_request]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

    - uses: leafo/gh-actions-lua@ea0ae38722c0b45aa4e770f7c4a650c6b26800d0 # v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@218573cd14f9a47b079c9b89349f9b71cb5ee706 # v4.0.0

    - name: setup
      run: |
        luarocks install luacheck

    - name: test
      run: |
        luacheck .

  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

    - uses: leafo/gh-actions-lua@ea0ae38722c0b45aa4e770f7c4a650c6b26800d0 # v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@218573cd14f9a47b079c9b89349f9b71cb5ee706 # v4.0.0

    - name: setup
      run: |
        luarocks install busted
        luarocks make

    - name: test
      run: |
        busted
